# Build settings
markdown: kramdown
#permalink: pretty
permalink: ':title/'


sass:
  sass_dir: assets/css
  style: :nested
 #style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: all