# Build settings

markdown: kramdown
permalink: pretty


include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested
# style: compressed (change to this when launching)

