# Build settings

markdown: kramdown
permalink: pretty

url: https://www.JessicaSchlesiger.ml   # with the https protocol
enforce_ssl: JessicaSchlesiger.ml   # without any protocol

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested
# style: compressed (change to this when launching)

