# Colors
mainAccent: "#003e85"
grayAccent: "#b0b0b0"
textColor: "#666"

# General Site Settings
title: Jessica Schlesiger Portfolio
description: Jessica Schlesiger's online portfolio.
email: Jessica.Schlesiger@gmail.com
location: Herndon, VA

# Navigation bar
menu:
- name: About
  url: /
- name: Portfolio
  url: /portfolio/
- name: Contact
  url: /contact/


# SEO Section
seo: Online portfolio for Jessica Schlesiger.

# Education
education:
 - school: Shippensburg University
   date: Fall 2014 - May 2018
   logo: ship.png
   title: Bachelor - Computer Science
   description: "Shippensburg University's computer science program is ABET accredited with Java and C as the main programming languages taught. The curriculum is concentrated on team building, design patterns, and good programming habits such as test-driven development."
   url: 
    - link: http://www.ship.edu/
      name: Ship.edu
   courses: 
    - Computer Science I
    - Computer Science II
    - Computer Organization
    - Design Patterns
    - Operating Systems
    - Compiler Design
    - Intro Computer Graphics
    - Artificial Intelligence
    - Computer Networks
    - Design and Analysis of Algorithms
    - Database Management
    - Big Data
    - Senior Research Methods
    - Senior Research and Development
   tech-blob:
    - Java, C, SQL, GLUT, OpenGL, Github, Eclipse, R, LISP, Assembly, Lua, Emacs, SourceForge, UML Design

# Experience
experience:
 - company: Wintech Corp
   date: April 2019 - Present
   logo: WintechCorp.png
   title: Software Developer
   description: "This project is a document conversion library which enables developers to validate, parse, transform, and serialize different XML data structures as needed. The project is utilized by a multitude of upstream and downstream systems to handle the numerous data formats without abrasion."
   url: 
    - link: http://wintechcorp.net/
      name: WintechCorp.net
   accomplishments:
    - Implemented support for a new format after a seven year support gap.
   tech-blob: 
    - Java, Kotlin, XSLT, XML, Intellij, Gradle, Github, JIRA, Agile, Jenkins, Microsoft Suite, Oxygen, HTML, Scala, Spark
 - company: HM Health Solutions
   date: June 2018 - April 2019
   logo: HMHS.png
   title: Associate IT Project Leader; Deployment Coordinator
   description: "This role required coordination with development teams and customers to maintain the stability of multiple large platforms. Ensuring successful and timely deployment for both application features and bug fixes required careful project planning and considerations to the business's upstream and downstream needs. Additionally, spare hours are spent optimizing workflow through creating macroscripts and streamlining systems."
   url: 
    - link: https://www.hmhs.com/index.shtml
      name: HMHS.com
   accomplishments:
    - Provided an estimated $100,000+ in annual savings by creating an AutoHotKey macro script to streamline document creation and processing.
    - Customized spreadsheet dashboards which utilized complicated conditional formatting formulas and Microsoft Visual Basic code to enable easier Change Request tracking for its user.
    - Given the responsibility of two large, unstable domains in an effort to improve current processes and behaviors. These platforms went from consistently requiring emergency releases weekly to successfully hitting their monthly benchmarks.
   tech-blob: 
    - Microsoft Suite, AutoHotKey, Microsoft Visual Basic
 - company: Hull Entertainment<br>Paint Nite & Plant Nite
   date: January 2016 - April 2018
   logo: PN.png
   title: Executive Assistant
   description: "The Executive Assistant works directly with the company owner and performs a variety of tasks dependant on the company's needs. It required coordinating with both local and remote employees who spanned across Central PA, Northern WV, Northern MD, and Portland, ME." 
   url: 
    - link: https://www.paintnite.com/
      name: PaintNite.com
    - link: https://www.plantnite.com/
      name: PlantNite.com
   accomplishments:
    - Automated event synchronization of the company's Google Calendar with its events spreadsheet. This eliminated human error and saved countless hours updating hundreds of events daily.
    - Created an automatic upcoming events email which would provided the employee with the location, time, size, and URL for their upcoming events.
    - Automated payroll summary creation to enable quick review of bi-weekly payroll entries. This allowed summarizing payroll to take less than five minutes rather than being an hour long manual process.
    - Created an employee information dashboard to enable quick lookup and review of employee information.
    - Implemented an ad-hock inventory management system utilizing Google Spreadsheets.
   tech-blob: 
    - JavaScipt, Java, Google API, Google Suite

# Skills
skills:
 - title: Programming
   items:
     - tag: Java
       value: 5
     - tag: JavaScript
       value: 5
     - name: Kotlin
       value: 4
     - name: Scala
       value: 3
     - tag: C
       value: 3
     - tag: jQuery
       value: 3
     - tag: HTML
       value: 5
     - tag: CSS
       value: 5
     - tag: SASS
       value: 4
     - name: XML
       value: 4
     - name: XSLT
       value: 4
     - tag: Jekyll
       value: 4
     - tag: Liquid
       value: 4
     - name: R
       value: 1
     - tag: SQL
       value: 2
     - name: Gradle
       value: 3
     - tag: AutoHotKey
       value: 5
     - name: Visual Basic
       value: 3
     - tag: Lua
       value: 2
     - tag: OpenGL
       value: 2
     - tag: GLUT
       value: 2
     - name: LISP
       value: 1
     - name: Assembly
       value: 1
     - name: Spark
       value: 1
 - title: Design
   items:
     - tag: Adobe Illustrator
       value: 4
     - tag: Adobe Photoshop
       value: 5
     - tag: Web Design
       value: 4
 - title: Utilities
   items:
     - name: Eclipse
       value: 4
     - name: Intellij
       value: 4
     - name: Notepad++
       value: 5
     - name: Github
       value: 5
     - name: SourceForge
       value: 2
     - name: Word
       value: 5
     - name: Excel
       value: 5
     - name: UML Design
       value: 5
     - name: Jenkins
       value: 2
     - name: Amazon Web Services (AWS)
       value: 3
     - name: JIRA
       value: 4

# Social Section
social:
- icon: 'github'
  link: 'https://github.com/schlesigerjess'
- icon: 'linkedin'
  link: 'https://www.linkedin.com/in/jessicaschlesiger/'
