#-------------------------------
# General Site Settings

title: Jessica Schlesiger Portfolio
description: Jessica Schlesiger's online portfolio.
email: Jessica.Schlesiger@gmail.com

menu:
- {name: About, url: '/'}
- {name: Portfolio, url: '/portfolio/'}
- {name: Contact, url: '/contact/'}

# SEO Section
seo:
  description: 'Online portfolio for Jessica Schlesiger.'

# Education
education_courses:
- {name: Computer Sci I-Lab Majors, id: CSC 107}
- {name: Computer Science I - Lecture, id: CSC 110}
- {name: Computer Science II, id: CSC 111}
- {name: Computer Organization, id: CMPE 220}
- {name: Design Patterns, id: SWE 200}
- {name: Operating Systems, id: CMPE 320}
- {name: Compiler Design, id: CSC 440}
- {name: Intro Computer Graphics, id: CSC 350}
- {name: Artificial Intelligence, id: CSC 462}
- {name: Computer Networks, id: CSC 431}
- {name: Design and Analysis of Algorithms, id: CSC 310}
- {name: Database Management, id: CSC 371}
- {name: Senior Research Methods, id: CSC 498}
- {name: Senior Research and Development, id: CSC 499}
- {name: Big Data, id: CSC 493}


# Experience
hullEntertainment_duties:
- {name: Script creation}
- {name: Scheduling events & staff}
- {name: Human resources}
- {name: Onboarding}
- {name: Maintaining file system}
- {name: Sumarize payroll}
- {name: Document creation}
- {name: Newsletter}

# Skills
skills_programming:
- {tag: C, value: 90}
- {name: Java, value: 100}
- {tag: JavaScript, value: 100}
- {tag: jQuery, value: 50}
- {tag: HTML, value: 100}
- {tag: CSS, value: 100}
- {tag: SASS, value: 100}
- {tag: Jekyll, value: 90}
- {tag: Liquid, value: 90}
- {tag: Lua, value: 40}
- {tag: OpenGL, value: 70}
- {tag: GLUT, value: 70}
- {name: R, value: 40}
- {tag: AutoHotKey, value: 80}
skills_design:
- {tag: Adobe Illustrator, value: 70}
- {tag: Adobe Photoshop, value: 90}
- {tag: Web Design, value: 80}
skills_utilities:
- {name: Eclipse, value: 100}
- {name: Notepad++, value: 100}
- {name: Github, value: 80}
- {name: SourceForge, value: 70}
- {name: Word, value: 100}
- {name: Excel, value: 100}
- {name: UML Design, value: 100}

# Social Section
social:
- {icon: 'github', link: 'https://github.com/schlesigerjess'}
- {icon: 'facebook', link: 'https://www.facebook.com/jessica.schlesiger'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jessicaschlesiger/'}