#-------------------------------
# General Site Settings

title: Jessica Schlesiger Portfolio
description: Jessica Schlesiger's online portfolio.
email: Schlesiger.Jess@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About, url: '/'}
- {name: Portfolio, url: '/portfolio/'}
- {name: Contact, url: '/contact/'}

#-------------------------------
# SEO Section

seo:
  description: 'Online portfolio for Jessica Schlesiger.'

#-------------------------------

# Education
education_courses:
- {name: Computer Sci I-Lab Majors, id: CSC 107}
- {name: Computer Science I - Lecture, id: CSC 110}
- {name: Computer Science II, id: CSC 111}
- {name: Computer Organization, id: CMPE 220}
- {name: Design Patterns, id: SWE 200}
- {name: Operating Systems, id: CMPE 320}
- {name: Compiler Design, id: CSC 440}
- {name: Intro Computer Graphic, id: CSC 350}
- {name: Artificial Intelligence, id: CSC 462}
- {name: Computer Networks, id: CSC 431}
- {name: Senior Research Methods, id: CSC 498}
- {name: Big Data, id: CSC 493}
- {name: Senior Research and Development, id: CSC 499}


# Experience
hullEntertainment_duties:
- {name: Automating processes}
- {name: Maintaining files}
- {name: Sumarize payroll}
- {name: Document creation}
- {name: Scheduling events & staff}
- {name: Human resources}
- {name: Onboarding}

# Skills

skills_programming:
- {name: C, value: '90', example: has Example}
- {name: JavaScript, value: '100', example: }
- {name: Java, value: '100', example: }
- {name: HTML, value: '90', example: has Example}
- {name: CSS, value: '90', example: has Example}
- {name: SASS, value: '90', example: has Example}
- {name: Jekyll, value: '70', example: has Exsdaample}
- {name: Liquid, value: '40', example: has Exsdaample}
- {name: Lua, value: '40', example: has Example}
- {name: OpenGL, value: '70', example: has Example}
skills_design:
- {name: Adobe Illustrator, value: '70', example: has Example}
- {name: Adobe Photoshop, value: '90', example: }
- {name: Web Design, value: '80', example: }
skills_utilities:
- {name: Eclipse, value: '100', example: }
- {name: Notepad++, value: '100', example: has Example}
- {name: Github, value: '80', example: has Example}
- {name: SourceForge, value: '70', example: has Example}
- {name: Word, value: '90', example: }
- {name: Excel, value: '90', example: }
- {name: UML, value: '100', example: has Example}

#-------------------------------
# Work Section

projects:
- {name: NEAT Neural Network, subName: "Research, Lua", folder: 'proj-6', file: 'work/proj-6.html', 
    description: "Testing for domain-general intelligence using a NEAT Neural Network in Super Mario World."}
- {name: Pheonix Atari 2600, subName: "C, OpenGL", folder: 'proj-1', file: 'work/proj-1.html',  
    description: "Recreation of the Atari arcade game Phenoix using OpenGL and C for my Intro To Computer Graphics project."}
- {name: Google Calendar Script, subName: "Javascript, Google Drive", folder: 'proj-4', file: 'work/proj-4.html', 
    description: "Scheduling script which pulls dates from a spreadsheet and updates or creates the events on designated Google Calendars."}
- {name: Email Notification Script, subName: Java, folder: 'proj-5', file: 'work/proj-5.html', 
    description: "Pulls data from the Employee Database and Upcoming Events Spreadsheet and notifies each staff member of upcoming events they are scheduled for."}
- {name: Pokemon Battle Simulator, subName: Java, folder: 'proj-2', file: 'work/proj-2.html', 
    description: aaaa}
- {name: Illustrations, subName: "Illustrator, Photoshop", folder: 'proj-7', file: 'work/proj-7.html', 
    description: "Hobbiest art creations."}
- {name: Graphic Design, subName: "Photoshop", folder: 'proj-8', file: 'work/proj-8.html', 
    description: aaaa}
- {name: Graaaaaaaphic Design, subName: "Photoshop", folder: 'proj-3', file: 'work/proj-3.html', 
    description: aaaa}
#-------------------------------
# Social Section

social:
- {icon: 'github', link: 'https://github.com/schlesigerjess'}
- {icon: 'facebook', link: 'https://www.facebook.com/jessica.schlesiger'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jessicaschlesiger/'}